// Module included in the following assemblies:
//
// * hosted_control_planes/hcp-deploy/hcp-deploy-aws.adoc

:_mod-docs-content-type: CONCEPT
[id="hcp-aws-prereqs_{context}"]
= Prerequisites to configure a management cluster

[role="_abstract"]
Before you can deploy {hcp} on {aws-first}, your environment must meet several requirements.

* Install the {mce} 2.5 and later on an {product-title} cluster. The {mce-short} is automatically installed when you install {rh-rhacm-first}. The {mce-short} can also be installed without {rh-rhacm} as an Operator from the {product-title} software catalog.

* Ensure that you have at least one managed {product-title} cluster for the {mce-short}. The `local-cluster` is automatically imported in the {mce-short} version 2.5 and later. You can check the status of your hub cluster by running the following command:
+
[source,terminal]
----
$ oc get managedclusters local-cluster
----

* Install the link:https://aws.amazon.com/cli/[`aws` command-line interface (CLI)].

* Install the hosted control plane CLI, `hcp`.

* Run the management cluster and compute nodes on the same platform.

* For each hosted cluster, provide a cluster-wide unique name. A hosted cluster name cannot be the same as any existing managed cluster in order for {mce-short} to manage it.

* Do not use `clusters` as a hosted cluster name.

* Do not create a hosted cluster in the namespace of a {mce-short} managed cluster.